name: Build LazyProxy.Autofac

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core 3.1.101
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Build
        run: find . -type f \( -iname "*.csproj" \) | xargs -n1 dotnet build
      - name: Test
        run: dotnet test ./LazyProxy.Autofac.Tests/LazyProxy.Autofac.Tests.csproj --no-build --verbosity normal
